[package]
name = "sudoku-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.14.0"
clap = "4.5.36"
rand = "0.9.0"
