pub mod solver;

mod eliminate_possibilities_using_existing_singles;
mod eliminate_possibilities_using_hidden_groups;
mod eliminate_possibilities_using_naked_pairs;
mod eliminate_possibilities_using_pointing;
mod eliminate_possibilities_using_y_wing;
mod set_naked_singles;
mod traits;
